version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      # Restore NuGet packages
     - dotnet restore
      # Build the .NET Core API project
     - dotnet build -c Release
      # Publish the project for deployment
     - dotnet publish -c Release -o ./publish
      # Create a ZIP archive of the publish folder
     - cd publish
     - zip -r ../dotnetcore-api-deployment-package.zip *
  post_build:
    commands:
      - aws s3api copy-object --copy-source codedeployforlambdap/BuildArtif --recursive --metadata-directive REPLACE --metadata "Content-Type=text/plain" --bucket codedeployforlambdap/BuildArtif --exclude "*" --include "**/*"

artifacts:
  files:
    - '**/*'
      
  
